name: flutter_course_1
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.4.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  condition: ^0.0.8
  flutter:
    sdk: flutter
  weather:
  url_launcher: 
  cupertino_icons: ^1.0.0
  geolocator: 
#  msix: ^1.0.3

dev_dependencies:
  http:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  #assets:
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf

    - family: SF
      fonts:
        - asset: assets/fonts/SF-UI-Display-Regular.otf



msix_config:
  display_name: StarTracker
  publisher_display_name: StarTracker
  #identity_name: MyCompany.MySuite.MyApp
  msix_version: 1.0.0.0